"""empty message

Revision ID: 857d06afd057
Revises: 129076cd8185
Create Date: 2022-08-11 21:20:32.856589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857d06afd057'
down_revision = '129076cd8185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_artists', sa.Integer(), nullable=False),
    sa.Column('id_venues', sa.Integer(), nullable=False),
    sa.Column('time_to_start', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_artists'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['id_venues'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
